name: Publish to Docker Hub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6.20']

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set PHP_MM_VERSION
        id: set_version
        run: echo "::set-output name=php_mm_version::$(echo "${{ matrix.php_version }}" | cut -d. -f1-2)"
      - name: Build the Docker image
        run: docker build --build-arg PHP_FULL_VERSION=${{ matrix.php_version }} --build-arg PHP_VERSION=${{ steps.set_version.outputs.php_mm_version }} . --file Dockerfile --tag jerrythomas/debian-php-fpm-dev:${{ matrix.php_version }}
      - name: Push to docker hub
        run: docker push jerrythomas/debian-php-fpm-dev:${{ matrix.php_version }}
